### ISSUE TITLE
Flow stops to work when reading multiple variables

### ISSUE THREAD

**Issue by icarogregorio** [netsmarttech/node-red-contrib-s7#10]
Hi, when we add some variables and do a full deployment the flow stops working and do not reinitialize the communication with PLC S7-1200.

**Comment by gfcittolin** [comment]
Here the data provided by Ícaro regarding the issue:
 - Variable table: [s7endpoint_PLC(2).csv.txt](https://github.com/netsmarttech/node-red-contrib-s7/files/1237191/s7endpoint_PLC.2.csv.txt)
 - Node-RED log: [log.txt](https://github.com/netsmarttech/node-red-contrib-s7/files/1237197/log.txt)

**Comment by gfcittolin** [comment]
The problem causing this was found and described in plcpeople/nodeS7#40, fix for this is in PR plcpeople/nodeS7#39

**Comment by gfcittolin** [comment]
Issue fixed in plcpeople/nodeS7 at 0.2.5
