### ISSUE TITLE
Array (6)  Real Error After Update V2.3 to V3.0

### ISSUE THREAD

**Issue by darecom** [netsmarttech/node-red-contrib-s7#100]
Hello I could always send an array (6) with real to my S7 1200 with node red and node-red-contrib-s7 V2.3. After update to node-red-contrib-s7 V3.0 this no longer works, I always get an error (see picture). I have not changed anything, besides updatring node-red-contrib-s7 V2.3 to V3.0

German: Hallo Ich konnte mit Node Red  und  node-red-contrib-s7 V2.3 immer einen Array (6) mit Real zu meiner S7 1200 schicken, Nach Update auf node-red-contrib-s7 V3.0 geht das nicht mehr es kommt immer ein Fehler (siehe Bild)  Ich habe nichts geändert , es wurde lediglich von node-red-contrib-s7 V2.3 auf V3.0 erhöht

![Array_Error](https://user-images.githubusercontent.com/93212237/138917576-44e73a70-a55b-450e-b152-06bfb77808a9.jpg)

**Comment by fernandoamorim1703** [comment]
Para que a leitura de arrays funcione corretamente, é preciso declarar dois colchetes, por exemplo

[[1,2,3,4]]

pois existe a possibilidade de escrever mais de um array de uma unica vez, ou seja, um array de arrays, por exemplo

[[2,2,2,2,2],[4,4,4,4]]
