### ISSUE TITLE
TSAP Settings Not Available

### ISSUE THREAD

**Issue by alberto464** [netsmarttech/node-red-contrib-s7#15]
Hello,

Tsap settings are not available, is there a way to turn them on?
The version of library is 1.3.1

<a href="http://it.tinypic.com?ref=zlz1qu" target="_blank"><img src="http://i65.tinypic.com/zlz1qu.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by gfcittolin** [comment]
That's weird, I see no way of hiding it. Also noticed the "Rack" icon is an old one, not the one we use on 1.3.x.
Maybe somehow the module was not updated, or then node-red was not restarted after the update, or even your browser is caching the resources. Could you check these points?

**Comment by alberto464** [comment]
I installed the library yesterday morning, I don't know how fix the problem

**Comment by gfcittolin** [comment]
Hi, I really couldn't simulate your issue. Are you still having this issue? Could you try a clean installation?
