### ISSUE TITLE
Word Timer

### ISSUE THREAD

**Issue by alberto464** [netsmarttech/node-red-contrib-s7#16]
Hello, I can not configure the days of the week (in the Timer) through WORD in my plc logo, I do not know which variable address to point.

**Comment by gfcittolin** [comment]
Hi, unfortunately we don't have any Logo here for testing. The support for Logo has been developed in a remote cooperation, therefore I can't tell you exactly how to interact with it.

What I can tell you is that you have to use a mapping of the addresses you want to access to DB1, you can check this link: https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PLC/LOGO.htm. Maybe you can try out mapping the value you want to read to one of these addresses mentioned in the link above, and then read it from Node-Red
