### ISSUE TITLE
Possible to use with other Siemens PLC devices?

### ISSUE THREAD

**Issue by MaartenV87** [netsmarttech/node-red-contrib-s7#24]
Is it possible to use this node with an Siemens Logo 8! PLC?
I'm looking to buy a Siemens Logo 8! but want to connect it to node-red. Can you help me? I think lots of people woulld be happy if this woulld be possible.

**Comment by gfcittolin** [comment]
Yes, it should be possible to use with Logo 8 by connecting using the TSAP settings. You can take a look at #5 where we discussed the implementation process and usage.
