### ISSUE TITLE
No response from PLC with S7-1500

### ISSUE THREAD

**Issue by noelkra** [netsmarttech/node-red-contrib-s7#27]
Hello

**Problem**
I have the problem that the node won't communicate with my PLC. It was working great on the S7-300 but on the S7-1500 I'm only getting the following error:

> "No response from PLC, restarting communication"

The connection is working but it can't communicate with the PLC → No output or variables change.

**Hardware/Software**
- S7-1500
- SIMATIC IOT2000
- NODE-RED v0.16.2
- node-red-contrib-s7 v1.5.1

Thank you for your help!

**Comment by gfcittolin** [comment]
Hi,

Please note that there are some differences between S7-300 and S7-1500. First, the Rack/Slot configuration differs between them. For S7-300 we have the default 0/2, and for S7-1500 we have 0/1 or 0/0.

Besides that, the 1200 and 1500 families may require some extra configuration on the PLC side, regarding access protection and DB optimization. Please check these [S7-1200/1500 Notes](http://snap7.sourceforge.net/snap7_client.html#1200_1500) for how to set them.
