### ISSUE TITLE
Emit only when value changes not working with array of bits

### ISSUE THREAD

**Issue by AlexanderLL95** [netsmarttech/node-red-contrib-s7#33]
Hi,

I think this is a new issue.

I found out how to read an array of bits from a PLC.
This is actually working. I get the correct values.

I use the following address to read the array of bits: DB60,X0.0.100

I checked the node property 'Emit only when value changes (diff)'.

This has no effect. The node ignores this setting.
The values are readed cyclic.

When i just ask for a specific bit. The setting is working.
See the screenshot of the debug output.

See the other screenshots for more details.

**Node configuration**
![image](https://user-images.githubusercontent.com/22889173/49687702-14605300-fb07-11e8-82d8-ead3225d5883.png)

**Flow**
![image](https://user-images.githubusercontent.com/22889173/49687706-2d690400-fb07-11e8-8c79-99103b93f47a.png)

**Debug output**
![image](https://user-images.githubusercontent.com/22889173/49687727-71f49f80-fb07-11e8-87e0-7aac59dc2088.png)

**Comment by gfcittolin** [comment]
Great catch! Indeed, we just check for plain javascript equality (`==`), and for arrays it won't work, as javascript will try to compare the references and will obviously fail (as they're not the same object, but may have the same content)
I'll try to fix it asap and report here so you can test it.

**Comment by AlexanderLL95** [comment]
Hi gfcittolin,
Thanks for the quick respons.
I'm looking forward for this fix.

**Comment by gfcittolin** [comment]
Just published 1.5.3 with the fix for that, sorry for the huge delay. Let me know if you have any other issue
