### ISSUE TITLE
works on PLCSIM but only get "bad values" on a real S7-1200

### ISSUE THREAD

**Issue by jupiter8888** [netsmarttech/node-red-contrib-s7#36]
Well, i will need a hand on this one,

every thing works o.k in simulation with PLCSIM,  so i changed the ethernet adress, complied, uploaded program in a s7-1200, started everything, tested o.k with TIA portal, can see values changing in my watch table and yes, put/get is enable, block optimisation disable and no protection is checked.

 I'm running Node-Red locally in the same laptop as TIA. 
 put the plc's ethernet address in the node. Without any variable the node is connected and no errors are reported. but with a variable i get "bad data" in the debug tab and "Error S7 endpoint : xxx Error connecting to PLC [object object]" in node-red debug window. 
i can ping the plc.
Nothing is changed, only ethernet address, same flow used for simulation.
Node-red V.0..19.6 
S7 node V.1.5.4

Even tried with a raspberry pi, same flow, same results, and i can ping the plc from the pi too.

any idea what can cause this?

Thanks.
![capture](https://user-images.githubusercontent.com/25290792/53813839-7b39b080-3f2c-11e9-972c-4b93a3021821.PNG)

**Comment by jupiter8888** [comment]
Finally nailed it. It looks like installed firmware version 4.1 was the culprit, afler installing version 4.2 it works.

But beware, i could'nt start the cpu after because of version mismatch, you have to replace the cpu from the catalog and reupload program and redownload it in TIA to make it work.

**Comment by gfcittolin** [comment]
I've already heard stories about fixing connection problems by upgrading the firmware, but it wouldn't cross my mind as a suggestion for this. Great that it worked after all, and thanks for sharing the solution!
