### ISSUE TITLE
"Error connecting to PLC" disturbing on Node-RED debug window if too many

### ISSUE THREAD

**Issue by MaFoB** [netsmarttech/node-red-contrib-s7#41]
In my application, many PLC connections are deployed.
A large number of PLCs is regularly switched off => connection "offline". In this case, the large number of messages "Error connecting to PLC" floods the Node-RED debug window, however, which is not dependent on the flow but on the connections. Thus, messages from debug nodes cannot be read anymore by the user.

How about a debug option "Off and no connection errors" at the connection properties ?
(The info "online/connecting/offline" ist still visible as green/yellow/red indicator at the node.)

**Comment by gfcittolin** [comment]
Yes, this could be a possibility. We could have a `Quiet` or `Silent` mode where all debug and warn messages would be suppressed (even though I fear about people complaining about the node not working, when in fact the error messages are not being shown).
Before we go for this option, have you tried changing the log levels on Node-RED itself?

**Comment by gfcittolin** [comment]
I was checking it out here, and there's an easier solution for that. You can use the `Catch` node on Node-RED to get the errors emitted by other nodes. Just tested it here, and you can suppress the error messages thrown because the PLC is offline.

**Comment by MaFoB** [comment]
Thank you for your answer. How do you suppress? Error is not thrown from node "s7 in" in the flow but from the configuration node in the background which still throws - see attachments:
![Config Node](https://user-images.githubusercontent.com/49685788/57684083-60bf3a00-7635-11e9-9035-7372d5572783.jpg)
![Config Node - Error thrown](https://user-images.githubusercontent.com/49685788/57684084-60bf3a00-7635-11e9-8442-98bd60672ab8.jpg)

**Comment by gfcittolin** [comment]
Try defining your config nodes to the flow scope, they come on the "All flows" (global) scope by default. You can configure that on the bottom right corner of the s7 endpoint configuration

**Comment by MaFoB** [comment]
Well, config nodes are just grouped then, "s7 endpoints" still throwing errors the same way, however...
![2019-05-14_13-10-23](https://user-images.githubusercontent.com/49685788/57693548-cb7a7080-7649-11e9-9f04-ba04d8badead.jpg)

**Comment by MaFoB** [comment]
... but - as I have experienced in the meantime - not in other flows anymore :)
> This is part of the solution, indeed.
> However, I still do not understand whether/how the Catch node can help in the flow where the error belongs to.

**Comment by gfcittolin** [comment]
When there's a Catch node catching errors thrown by other nodes, they're not shown on the debug window. This is the behavior I have (and that's what I've expected you'd have too)
![Peek 2019-05-16 15-33](https://user-images.githubusercontent.com/2856088/57878421-5eeda600-77f0-11e9-9656-c2fe48c88058.gif)

**Comment by MaFoB** [comment]
I found out that after deployment of the Catch node in a flow I need to restart Node-Red to have the behavior as shown and expected.
Before it is like this:
![Catch_before_NR_restarted](https://user-images.githubusercontent.com/49685788/58183870-5abdfe80-7cb0-11e9-9499-0f07dbaaba27.jpg)

Thank you very much for your support !
