### ISSUE TITLE
Set variable list dynamically

### ISSUE THREAD

**Issue by thsmr** [netsmarttech/node-red-contrib-s7#54]
Hi all,

I would like to read a dynamic list of variables from the plc (the variable list could change over time).
Would it be possible to implement such a feature on the "s7 control" node?

My use case is as follows:
I would like to read a list of parameters (name and address) from a database, read them from the plc and write them back to the database.

**Comment by gfcittolin** [comment]
We'll be centering the discussion around this feature on #63
