### ISSUE TITLE
DATE_AND_TIME

### ISSUE THREAD

**Issue by boldt** [netsmarttech/node-red-contrib-s7#55]
I miss the datatye `DATE_AND_TIME`. A direct convertion into a `Date()`-object would be awesome.

Here is the spec: https://support.industry.siemens.com/cs/document/36479/date_and_time-format-for-s7-?dti=0&lc=en-WW

**Comment by gfcittolin** [comment]
Hi, thanks for the suggestion, this is something also on my whishlist. The implementation of data types needs to be done at nodes7, I'll therefore transfer the issue to that repository.

**Comment by gfcittolin** [comment]
implemented on the just published 2.2.0
