### ISSUE TITLE
Node says: SyntaxError: Unexpected identifier (line:38)

### ISSUE THREAD

**Issue by SammyGoderis** [netsmarttech/node-red-contrib-s7#58]
![Knipsel](https://user-images.githubusercontent.com/59192156/71397924-3a2b9d80-261f-11ea-9bd1-ae8b9ae54b3c.PNG)

The node is also not shown on the left.
IOT2000
V0.19.5

**Comment by SammyGoderis** [comment]
Delete version 2.1.0 and install 2.0.2 did work.

"npm install node-red-contrib-s7@2.0.2"

**Comment by gfcittolin** [comment]
You're probably using an outdated version of Node.JS. Please check by running `node -v`. The minimum supported version is 6.x

**Comment by kbogusz** [comment]
After updating NodeJS to latest version I also had issues with installing s7node at all. Unfortunately I didn't save any screenshots..

**Comment by gfcittolin** [comment]
Could you please try to reproduce the error and post logs and/or screenshots?

**Comment by gfcittolin** [comment]
Closing the issue due to lack of activity. Please feel free to reopen it if the issue persists.
