### ISSUE TITLE
Error connecting to PLC: [object Object]

### ISSUE THREAD

**Issue by next36eee** [netsmarttech/node-red-contrib-s7#77]
### Describe the bug
This library works like a charm, i found a bug that even after deleting the S7 nodes from my flow but it is continuously giving an error message in the Debug which says that Error connecting to PLC: [object Object] 

### Environment
 - **Version** of this node: 2.2.1
 - **Node-RED version**: 1.1.3
 - **OS**: Windows 10
 - **Browser**: chrome

**Comment by sniicker** [comment]
What was your Solution - same problem here

**Comment by next36eee** [comment]
@sniicker In the configuration node(can be found in the options menu), you have to delete the S7-end point and then you will not get any error

**Comment by sniicker** [comment]
I cannot delete the node, this is my active s7 endpoint


-------- Ursprüngliche Nachricht --------
Von: next36eee <notifications@github.com>
Datum: 24.02.21 14:04 (GMT+01:00)
An: st-one-io/node-red-contrib-s7 <node-red-contrib-s7@noreply.github.com>
Cc: Philipp <philipp.sojer@hotmail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [st-one-io/node-red-contrib-s7] Error connecting to PLC: [object Object] (#77)


@sniicker<https://github.com/sniicker> In the configuration node(can be found in the options menu), you have to delete the S7-end point and then you will not get any error
